export const STORIES_ADD = 'STORIES_ADD';
export const STORIES_ADD_SEARCH = 'STORIES_ADD_SEARCH';
export const STORIES_LOADING = 'STORIES_LOADING';
export const STORIES_FAILED = 'STORIES_FAILED';
export const STORIES_INCREMENT_PAGE_NUMBER = 'STORIES_INCREMENT_PAGE_NUMBER';
export const STORIES_SET_FILTER_COMIC_ID = 'STORIES_SET_FILTER_COMIC_ID';